### PR TITLE
fixes as requested by cory/gonzalo

### PR DESCRIPTION
**Pull request by daattali**

### CODE REVIEW

**Comment by gepinillab** [comment]
Hi Dean (cc @cmerow),

Thanks for all the fixes. The new close button and the scrollbar are working without problems.

The only thing that is not working is the disable_module() function. There was a typo in the module argument in modules/userEnvs.R#103. After changing it to the correct module name, it is still not working.
`common$disable_module(component = "proj", module = "proj_time")`

I also checked the remove_module() before your pull request, which is not working either.

Please let me know if you need some info to solve this issue.

Best,
Gonzalo

**Comment by daattali** [comment]
I just tried the following and it worked:

To ui.R I added `actionButton("test", "test")`

To server.R I added `observeEvent(input$test, common$disable_module("proj", "time"))`

**Comment by gepinillab** [comment]
Dean, 

Thanks for the clarification. It worked. I also did some testing with the enable_module(). Everything is working without problems.

Is it possible to add personalized text instead of the disable icon when placing the mouse cursor in a disable module? Is this something that you can include as an argument in disable_module()?

Gonzalo

**Comment by daattali** [comment]
It is possible, but it's not a quick 10 minute thing to add, it'll require some time to research the best way, try out different implementations, and test.

**Comment by gepinillab** [comment]
Okay, no problem. Maybe it will be something to add in the future. 

Thanks again for all the fixes!

**Pull request merged**
